# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='like',
            name='messages',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wall_app.Comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wall_app.Message'),
        ),
    ]
